export const runtime = "edge";

export default function PrivacyPolicyPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-16 text-sm text-slate-700">
      <h1 className="text-2xl font-semibold text-slate-900 mb-2">
        Privacy Policy
      </h1>
      <p className="mb-6 text-xs text-slate-500">
        Last updated: January 27, 2026
      </p>

      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>

      <p className="mb-4">
        We use information to provide and improve the Service. By using the
        Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      <h2 className="font-semibold text-slate-900 mt-6 mb-2">
        Interpretation and Definitions
      </h2>

      <h3 className="font-medium text-slate-800 mt-4 mb-1">
        Interpretation
      </h3>
      <p className="mb-4">
        The words whose initial letters are capitalized have meanings defined
        under the following conditions. The following definitions shall have
        the same meaning regardless of whether they appear in singular or plural.
      </p>

      <h3 className="font-medium text-slate-800 mt-4 mb-1">
        Definitions
      </h3>
      <p className="mb-3">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc list-inside space-y-2 mb-4">
        <li>
          <strong>Company</strong> (referred to as either &quot;the Company&quot;,
          &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;) refers to PIH Digital
          INC, 71–75 Shelton Street, Covent Garden, London, WC2H 9JQ, United
          Kingdom.
        </li>
        <li>
          <strong>Website</strong> refers to PixoConvert, accessible from{" "}
          <a
            href="https://www.pixoconvert.com/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 underline"
          >
            https://www.pixoconvert.com
          </a>
          .
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself.
        </li>
        <li>
          <strong>Cookies</strong> are small files placed on Your device to
          remember certain information and preferences.
        </li>
      </ul>

      <h2 className="font-semibold text-slate-900 mt-6 mb-2">
        Collecting and Using Your Data
      </h2>

      <h3 className="font-medium text-slate-800 mt-4 mb-1">
        Types of Data Collected
      </h3>

      <h4 className="font-medium text-slate-800 mt-4 mb-1">
        Usage Data
      </h4>
      <p className="mb-4">
        Usage Data is collected automatically when using the Service. Usage Data
        may include information such as Your device&apos;s IP address, browser
        type, browser version, pages visited, the time and date of Your visit,
        time spent on pages, and other diagnostic data.
      </p>

      <h4 className="font-medium text-slate-800 mt-4 mb-1">
        Uploaded Images and File Processing
      </h4>
      <p className="mb-4">
        PixoConvert allows You to upload image files solely to perform file
        conversion. Uploaded files are processed automatically and are not
        reviewed manually.
      </p>
      <p className="mb-4">
        Files may be temporarily stored only as necessary to complete the
        conversion process and are automatically deleted after processing.
      </p>

      <h3 className="font-medium text-slate-800 mt-4 mb-1">
        Tracking Technologies and Cookies
      </h3>
      <p className="mb-4">
        We use Cookies and similar tracking technologies to track activity on
        Our Service and store certain information. You can instruct Your browser
        to refuse all Cookies or to indicate when a Cookie is being sent. If You
        do not accept Cookies, some parts of the Service may not function
        properly.
      </p>

      {/* ✅ AdSense required disclosure */}
      <h2 className="font-semibold text-slate-900 mt-6 mb-2">
        Advertising (Google AdSense)
      </h2>
      <p className="mb-4">
        We display advertisements on this website, including ads served by
        Google and other third-party vendors.
      </p>
      <p className="mb-4">
        Third-party vendors, including Google, use cookies to serve ads based on
        a user&apos;s prior visits to this website and/or other websites.
      </p>
      <p className="mb-4">
        Google&apos;s use of advertising cookies enables it and its partners to
        serve ads to users based on their visit to this site and/or other sites
        on the Internet.
      </p>
      <p className="mb-4">
        You may opt out of personalized advertising by visiting Google&apos;s
        Ads Settings:
        {" "}
        <a
          href="https://www.google.com/settings/ads"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-600 underline"
        >
          https://www.google.com/settings/ads
        </a>
        .
      </p>
      <p className="mb-4">
        You can also manage cookies through your browser settings and, where
        applicable, through any cookie consent tools provided on the site.
      </p>

      <h3 className="font-medium text-slate-800 mt-4 mb-1">
        How We Use Information
      </h3>
      <ul className="list-disc list-inside space-y-2 mb-4">
        <li>To provide and maintain the Service</li>
        <li>To monitor usage and improve performance and reliability</li>
        <li>To respond to requests and support inquiries</li>
        <li>To help display and measure advertising</li>
      </ul>

      <h3 className="font-medium text-slate-800 mt-4 mb-1">
        Retention of Data
      </h3>
      <p className="mb-4">
        We retain information only for as long as necessary for the purposes set
        out in this Privacy Policy, including security, troubleshooting, and
        legal compliance.
      </p>
      <p className="mb-4">
        Uploaded images are stored temporarily only as needed to perform the
        conversion and are automatically deleted after processing.
      </p>

      <h3 className="font-medium text-slate-800 mt-4 mb-1">
        Security
      </h3>
      <p className="mb-4">
        The security of Your information is important to Us, but remember that
        no method of transmission over the Internet or electronic storage is 100%
        secure. We strive to use commercially acceptable means to protect
        information, but cannot guarantee absolute security.
      </p>

      <h2 className="font-semibold text-slate-900 mt-6 mb-2">
        Children&apos;s Privacy
      </h2>
      <p className="mb-4">
        Our Service does not knowingly collect personally identifiable
        information from anyone under the age of 16. If You are a parent or
        guardian and You believe Your child has provided Us with Personal Data,
        please contact Us.
      </p>

      <h2 className="font-semibold text-slate-900 mt-6 mb-2">
        Links to Other Websites
      </h2>
      <p className="mb-4">
        Our Service may contain links to other websites that are not operated by
        Us. If You click a third-party link, You will be directed to that third
        party&apos;s site. We strongly advise You to review the Privacy Policy
        of every site You visit.
      </p>

      <h2 className="font-semibold text-slate-900 mt-6 mb-2">
        Changes to this Privacy Policy
      </h2>
      <p className="mb-4">
        We may update Our Privacy Policy from time to time. Changes are
        effective when they are posted on this page.
      </p>

<h2 className="font-semibold text-slate-900 mt-8 mb-2">
  Advertising and Third-Party Cookies
</h2>

<p className="mb-4">
  We use third-party advertising companies, including Google AdSense, to serve
  ads when you visit our Website. These companies may use cookies or similar
  technologies to display advertisements to users based on their visits to this
  and other websites.
</p>

<p className="mb-4">
  Google, as a third-party vendor, uses cookies (including the DoubleClick
  cookie) to serve ads to users based on their prior visits to our Website or
  other websites on the Internet.
</p>

<p className="mb-4">
  Users may opt out of personalized advertising by visiting{" "}
  <a
    href="https://adssettings.google.com"
    target="_blank"
    rel="noopener noreferrer"
    className="text-blue-600 underline"
  >
    Google Ads Settings
  </a>.
</p>

<p className="mb-4">
  For more information about how Google manages data in advertising products,
  please see{" "}
  <a
    href="https://policies.google.com/technologies/ads"
    target="_blank"
    rel="noopener noreferrer"
    className="text-blue-600 underline"
  >
    Google Advertising Policies
  </a>.
</p>



      

      <h2 className="font-semibold text-slate-900 mt-6 mb-2">
        Contact Us
      </h2>
      <p className="mb-4">
        If you have any questions about this Privacy Policy, You can contact us
        at{" "}
        <a
          href="mailto:support@pixoconvert.com"
          className="text-blue-600 underline"
        >
          support@pixoconvert.com
        </a>
        .
      </p>
    </main>
  );
}
